### ISSUE TITLE
上下滑动失效

### ISSUE THREAD

**Issue by 401885064** [ta893115871/StickyNavLayout#1]
我的布局是fragment里嵌套了一个fragment     在里面的fragment里实现界面：界面布局如下：

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    android:id="@+id/home_top_layout"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:custom="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

```
<com.sondon.mayi.ui.MyMultipleTopBar
    android:id="@+id/topBar"
    android:layout_width="match_parent"
    android:layout_height="@dimen/topbar_layout_height_size"
    android:background="@color/main_tabbar_backage_color"
    custom:drawable_left="@drawable/home"
    custom:drawable_right="@drawable/search"
    custom:have_left="true"
    custom:have_left_drawable="true"
    custom:have_right="true"
    custom:have_right_drawable="true"
    custom:have_title="true"
    custom:have_title_drawable="false"
    custom:leftText=""
    custom:leftTextColor="@android:color/white"
    custom:rightText=""
    custom:rightTextColor="@android:color/white"
    custom:title="首页"
    custom:titleTextColor="@android:color/white"
    custom:titleTextSize="@dimen/topbar_title"/>

<com.gxz.library.StickyNavLayout
    android:id="@+id/id_stick"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:stick="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    stick:isStickNav="true">

    <LinearLayout
        android:id="@id/id_stickynavlayout_topview"
        android:layout_width="match_parent"
        android:layout_height="170dp"
        android:background="#fee"
        android:orientation="vertical">

        <com.minking.imagecycleview.ImageCycleView
            android:id="@+id/ad_view"
            android:layout_width="match_parent"
            android:layout_height="170dp"
            />
    </LinearLayout>

    <com.shizhefei.view.indicator.ScrollIndicatorView
    android:id="@+id/id_stickynavlayout_indicator"
    android:layout_width="match_parent"
    android:layout_height="40dp"
    android:fillViewport="false"/>

    <android.support.v4.view.ViewPager
    android:id="@+id/id_stickynavlayout_viewpager"
    android:layout_width="match_parent"
    android:layout_height="match_parent"/>
</com.gxz.library.StickyNavLayout>
```

</LinearLayout>

现在是程序跑起来没问题， 只是不能上下滑动  只可以左右滑动，   ViewPager里是Fragment   布局如下是:

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@color/page_backage_color"
              android:orientation="vertical">

```
<com.handmark.pulltorefresh.library.PullToRefreshListView
    android:id="@+id/pull_list"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginLeft="7dp"
    android:layout_marginRight="7dp"
    android:descendantFocusability="afterDescendants"
    android:fadingEdge="none"
    android:divider="@null"
    android:fastScrollEnabled="false"
    android:listSelector="#00000000"
    android:scrollbars="none"
    android:smoothScrollbar="true"
    android:visibility="visible"
    app:ptrMode="both"/>
```

</LinearLayout>

麻烦能帮忙看一下是什么原因吗？？

**Comment by ta893115871** [comment]
<com.handmark.pulltorefresh.library.PullToRefreshListView
    android:id="@+id/pull_list"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_marginLeft="7dp"
    android:layout_marginRight="7dp"
    android:descendantFocusability="afterDescendants"
    android:fadingEdge="none"
    android:divider="@null"
    android:fastScrollEnabled="false"
    android:listSelector="#00000000"
    android:scrollbars="none"
    android:smoothScrollbar="true"
    android:visibility="visible"
    app:ptrMode="both"/>   

这个listview 的id应该为android:id="@+id/id_stickynavlayout_innerscrollview"

**Comment by 401885064** [comment]
设置Id后，发现是不支持PullToRefreshListView组件？  我换成ListView组件就可以滑动了。。。 但我需要listView下拉刷新  上啦加载功能，改如何破？

**Comment by 401885064** [comment]
能实现下拉加载更多吗？

**Comment by ta893115871** [comment]
可以实现下拉刷新，下拉的你时用的PullToRefreshListView，暂时不支持这个下拉刷新控件。你可以参考demo中的那个下拉刷新的控件
