### ISSUE TITLE
我设置了isStickNav和stickOffset 但是不起作用

### ISSUE THREAD

**Issue by maomizone** [ta893115871/StickyNavLayout#11]
debug到StickyNavLayout后 发现值没有取得，这是为啥啊
 <com.gxz.library.StickyNavLayout
        android:id="@+id/id_stick"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        stick:isStickNav="true"
        stick:stickOffset="44dp">
这样写不对吗

**Comment by ta893115871** [comment]
你用的什么版本

**Comment by maomizone** [comment]
1.2，刚刚把属性自己工程定义后可以了，但有一个问题stickOffset 的作用，我看说明是上滑过程，吸附区域距离顶部stickOffset 就开始吸附在那儿，但实际操作时候发现是让topview的高度减去了这一部分，没有起到【吸附区域距离顶部stickOffset 就开始吸附在那儿】

**Comment by maomizone** [comment]
LZ,看了代码后，发现onMeasure()  this.mTopViewHeight = topParams.height;-------->
this.mTopViewHeight = topParams.height - stickOffset;就可以了，非常好的开源项目，项目用上了

**Comment by ta893115871** [comment]
嗯

**Comment by ta893115871** [comment]
@maomizone  嗯，修改top区域隐藏显示问题 该出来的bug，后期版本修改下
