### ISSUE TITLE
请问大神能够控制tab区域停靠再某个控件之下吗？

### ISSUE THREAD

**Issue by oksimple** [ta893115871/StickyNavLayout#12]
我看了demo 好像全是停靠再屏幕最上方，但是我现在需求是 让他停靠在某个控件之下，比如 tab上面 还有好几个控件 我想让滑动时候 让他停靠在 其中一个控件之下。

**Comment by ta893115871** [comment]
@oksimple   可以利用设置stickOffset 来调节高度，你可以试下
