### ISSUE TITLE
下拉刷新也是用的您的！

### ISSUE THREAD

**Issue by laconichy** [ta893115871/StickyNavLayout#17]
我怎么用下拉刷新来更新Viewpager中RecyclerView的数据呢？

**Comment by ta893115871** [comment]
下拉刷新demo中的是开源的，这个随便

**Comment by laconichy** [comment]
怎么监听Tab栏呢？ @FlyInTheSkyToMe  什么意思？有个是否悬浮的监听，demo里面有

**Comment by laconichy** [comment]
我在刷新ViewPager里面的内容时， 用到了回调。但是出现冲突和bug了。

什么冲突？

**Comment by laconichy** [comment]
下拉刷新 里面有个参数， 具体是什么呢？干什么用的？

**Comment by ta893115871** [comment]
@FlyInTheSkyToMe  那个下来刷新有别人开源的，里面的参数都是一些对下拉的控制，可以参考那个下拉的文档
