### ISSUE TITLE
listview使用了加载更多之后，出现问题。。。

### ISSUE THREAD

**Issue by LinF2015** [ta893115871/StickyNavLayout#18]
listview和recycleview使用了加载更多之后，出现底部显示不全，，，还有就是偶尔会出现一个跳动的空白布局，，不知道我哪里写错了

**Comment by LinF2015** [comment]
标题是在StickyNavLayout的外面，高度为50dp，然后listview最下面总是计算少了50dp ，，拉动刷新就会在底部出现跳动的空白布局，不知道该怎么解决？

**Comment by ta893115871** [comment]
什么版本？

**Comment by ta893115871** [comment]
可以加我QQ 893115871

**Comment by LinF2015** [comment]
谢谢你，已经解决了，是我的问题，，你的项目很好

**Comment by ta893115871** [comment]
搜噶
