### ISSUE TITLE
SimpleStickActivity里面onCreate里设置 stickyNavLayout.setScrollY(0)为什么无效？

### ISSUE THREAD

**Issue by messishow** [ta893115871/StickyNavLayout#19]
SimpleStickActivity一打开最上面就是就是悬浮框，需要下拉才能看到TOP-VIEW，我想一打开就能看到TOP-VIEW，所以在onCreate里设置stickyNavLayout.setScrollY(0)，但是没有效果

**Comment by ta893115871** [comment]
看下使用说明 readme ，SimpleStickActivity 的布局文件 该控件有个属性 stick:isStickNav="true" ，我是为了演示demo，你可以去了

**Comment by messishow** [comment]
嗯，我设置了stick:isStickNav="true"，已经一打开页面有TOP-VIEW的内容了，但是这时候往上滑动的时候TOP-VIEW的部分不动，只是下面listview的item往上滑动

**Comment by messishow** [comment]
找到原因了，scrollTo()先于onMeasure()执行，所以刚进去的时候mTopViewHeight==0，导致isTopHidden=true，实际上isTopHidden应该等于false

**Comment by messishow** [comment]
在onMeasure()里面重新isTopHidden = getScrollY() == mTopViewHeight就好了

**Comment by ta893115871** [comment]
根据你的描述，你这个设置了     stick:stickOffset="20dp" 属性吧

**Comment by messishow** [comment]
没有设置stick:stickOffset="20dp" 属性，这个问题的原因是scrollTo()先于onMeasure()执行，所以刚进去的时候mTopViewHeight==0，导致isTopHidden=true，实际上isTopHidden应该等于false
