### ISSUE TITLE
进入ScrollViewFragment和GridViewWithHeaderAndFooterFragment会闪退

### ISSUE THREAD

**Issue by hexuejian** [ta893115871/StickyNavLayout#26]
@

**Comment by hexuejian** [comment]
![qq 20160923160528](https://cloud.githubusercontent.com/assets/12168326/18778597/9c8931a6-81a7-11e6-9a70-ffa1afe02efe.png)

**Comment by ta893115871** [comment]
这有好像是GridViewWithHeaderAndFooter这个开源库的问题，你可以尝试去了这个fragment
