### ISSUE TITLE
使用RecyclerView，适配器中动态隐藏某个item, 滑到顶部之后出现滑不下来现象

### ISSUE THREAD

**Issue by LinF2015** [ta893115871/StickyNavLayout#27]

**Comment by RuiRay** [comment]
我也遇到了滑到顶部后，滑不下来的问题。可能与你的问题一致。

描述：在 RecyclerView 滑到顶部后，再往下滑动时头部的 View 无法滑下来。如果没有滑到顶部，向下滑动没有问题，并且偶尔能够滑下来。

原因：我在 mRecyclerView.addItemDecoration() 中设置了 outRect.top，导致 rv.getChildAt(0).getTop() == 0 的判断不成立，父布局无法拿滑动事件。

解决：由于设置 outRect.top 的值等于 rv.getChildAt(0).getTop()，因此可以更改条件（**rv.getChildAt(0).getTop() == outRect.top**），或让 **outRect.top = 0**。

**Comment by LinF2015** [comment]
谢谢，我也解决了
