### ISSUE TITLE
头部超出一屏会出现头部计算错误

### ISSUE THREAD

**Issue by WuxuFanhua** [ta893115871/StickyNavLayout#28]
开发的时候发现，ScrollView内部布局复杂，有动态加载进入的View后，被截断，只能显示首屏内容，分析后发现，高度计算错误。

解决方法如下
        //修复键盘弹出后Top高度不对问题
        int topHeight = mTop instanceof ViewGroup ? ((ViewGroup) mTop).getChildAt(0).getMeasuredHeight() : mTop.getMeasuredHeight();
        ViewGroup.LayoutParams topParams = mTop.getLayoutParams();

**Comment by sqsong66** [comment]
@WuxuFanhua 我这儿也遇到一个问题，当id_stickynavlayout_topview的高度大于一屏的时候id_stickynavlayout_indicator悬浮条显示不完整，请问一下你又碰到这个问题吗？

**Comment by WuxuFanhua** [comment]
@songmao123  没遇到。。。。我是topview 未显示完整，被截断了。

**Comment by sqsong66** [comment]
@WuxuFanhua 知道了，我把那个id_stickynavlayout_indicator的View的高度设为wrap_content了就出现那种情况了，设置成具体的dp就不会出现这个问题了。谢啦

**Comment by MrUncleYzw** [comment]
@WuxuFanhua 请问你解决了么，我这也遇到同样的问题

**Comment by WuxuFanhua** [comment]
@MrUncleYzw  在测量高度的里面，找到测量top高度的
改成这个就可以了。我是这样解决的。
int topHeight = mTop instanceof ViewGroup ? ((ViewGroup) mTop).getChildAt(0).getMeasuredHeight() : mTop.getMeasuredHeight();
ViewGroup.LayoutParams topParams = mTop.getLayoutParams();

**Comment by MrUncleYzw** [comment]
@WuxuFanhua  谢谢，我昨天解决了，类似的方法，感谢回复
