### ISSUE TITLE
top内容变化的问题

### ISSUE THREAD

**Issue by yankai-victor** [ta893115871/StickyNavLayout#3]
你好，我在实际使用中遇到了一些小问题。
我使用的topview是scrollview，里面包含了Textview。当我设置Textview的text的时候，如果textview为两行以上时，scrollview的高度不会增加，这样使得底部的部分控件被挤压而隐藏了。
请问这个问题有什么解决思路吗？

**Comment by ta893115871** [comment]
demo里面有 ，你可以参考下
