### ISSUE TITLE
无法滑动问题

### ISSUE THREAD

**Issue by BryceLee** [ta893115871/StickyNavLayout#30]

**Comment by BryceLee** [comment]
<?xml version="1.0" encoding="utf-8"?>
<in.srain.cube.views.ptr.PtrClassicFrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:cube_ptr="http://schemas.android.com/apk/res-auto"
    xmlns:pst="http://schemas.android.com/apk/res-auto"
    xmlns:stick="http://schemas.android.com/apk/res-auto"
    android:id="@+id/store_house_ptr_frame"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    cube_ptr:ptr_duration_to_close="300"
    cube_ptr:ptr_duration_to_close_header="2000"
    cube_ptr:ptr_keep_header_when_refresh="true"
    cube_ptr:ptr_pull_to_fresh="false"
    cube_ptr:ptr_ratio_of_header_height_to_refresh="1.2"
    cube_ptr:ptr_resistance="1.7">
    
    <com.gxz.library.StickyNavLayout xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/id_stick"
        app:isStickNav="false"

```
    >

    <RelativeLayout
        android:id="@id/id_stickynavlayout_topview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#4400ff00">

        <TextView
            android:layout_width="match_parent"
            android:layout_height="256dp"
            android:gravity="center"
            android:text="软件介绍"
            android:textSize="30sp"
            android:textStyle="bold" />
    </RelativeLayout>

    <!--<LinearLayout-->
        <!--android:layout_width="match_parent"-->
        <!--android:layout_height="wrap_content"-->
        <!--android:background="#FFFFFF"-->
        <!--android:orientation="horizontal">-->
    <com.gxz.PagerSlidingTabStrip
        android:id="@+id/id_stickynavlayout_indicator"
        android:layout_width="match_parent"
        android:layout_height="48dp"
        android:textSize="16sp"
        pst:pstsDividerColor="@color/colorPrimary"
        pst:pstsIndicatorColor="@color/colorPrimary"
        pst:pstsIndicatorHeight="5dp"
        pst:pstsScaleZoomMax="0"
        pst:pstsShouldExpand="false"
        pst:pstsTextSelectedColor="#303F9F"
        pst:pstsUnderlineColor="@color/colorPrimary" />



    <android.support.v4.view.ViewPager
        android:id="@id/id_stickynavlayout_viewpager"
        android:layout_width="match_parent"
        android:layout_height="match_parent"></android.support.v4.view.ViewPager>

</com.gxz.library.StickyNavLayout>
```

</in.srain.cube.views.ptr.PtrClassicFrameLayout>
运行后无法滑动，请问有可能是什么问题呢？

**Comment by BryceLee** [comment]
我把Demo里面PullToRefreshStickActivity的content_pull_to_refresh布局复制到项目里，运行，还是无法滑动。

**Comment by ta893115871** [comment]
看下ViewPager内部的listview 等控件的id 必须为id_stickynavlayout_innerscrollview
