### ISSUE TITLE
top里如果指定一个view隐藏View.Gone的时候 页面会留白 求给个思路

### ISSUE THREAD

**Issue by 1izheng** [ta893115871/StickyNavLayout#4]
页面操作后 设置了几个控件隐藏,会导致top高度还是原来的高度 隐藏的控件会留白,求解如何解决 给个思路

**Comment by ta893115871** [comment]
暂时可以通过StickyNavLayout  setTopViewHeight 方法设置；
后期看看能不能自动处理

**Comment by ta893115871** [comment]
1.2版本修复了
