### ISSUE TITLE
SticyNavLayout改成继承至ReleativeLayout,内部的控件（ViewPager）高度不对了，造成底部空白

### ISSUE THREAD

**Issue by qiaobacmm** [ta893115871/StickyNavLayout#6]
SticyNavLayout改成继承至ReleativeLayout,内部的控件（ViewPager）高度不对了，造成底部空白，
请问下为什么呢

**Comment by ta893115871** [comment]
那你需要设置ViewPager高度吧，用linear layout竖直排列的
