### ISSUE TITLE
支持MaterialRefreshLayout么

### ISSUE THREAD

**Issue by smuyyh** [ta893115871/StickyNavLayout#8]
MaterialRefreshLayout是嵌套ListView的，而不是在最外面布局。这样可以么？

**Comment by smuyyh** [comment]
MaterialRefreshLayout是嵌套ListView的，而不是在最外面布局。这样可以么？

**Comment by ta893115871** [comment]
你说的是SwipeRefreshLayout吗？里面有个小例子可以作为参考

**Comment by smuyyh** [comment]
那个是在最外面布局，我意思是能不能SwipeRefreshLayout只包住ListView的~

**Comment by ta893115871** [comment]
这不支持

**Comment by ta893115871** [comment]
这个目前不支持，刷新数据一般都是这个页面下拉刷新吧，嘻嘻😄

**Comment by smuyyh** [comment]
主要是事件那部分没怎么看懂。还是谢谢啦~~

**Comment by ta893115871** [comment]
@smuyyh   嗯
