### ISSUE TITLE
ViewPager可以换成RecyclerView吗

### ISSUE THREAD

**Issue by maoxiandemeng** [ta893115871/StickyNavLayout#9]
ViewPager可以换成RecyclerView吗，会有这样的需求，标题只是不同的类型，调用的接口是一样的，就不需要写成ViewPager的

**Comment by ta893115871** [comment]
你的意思是 ViewPager里面是一个RecyclerView？

**Comment by maoxiandemeng** [comment]
我的意思是不用ViewPager，就一个RecyclerView，我改了你的代码可以了，我换成RecyclerView把id设为inner的那个，注释掉从ViewPager的Adapter里找inner部分。有一点问题，我设了stickOffset属性的值，一开始从RecyclerView部分滑动，只滑动RecyclerView部分，不是整体滑动，一开始从头部滑动就没有什么问题

**Comment by ta893115871** [comment]
stickOffset设置了多大呀，这个值超过了top区域的高度 肯定就不会悬浮了。
stickOffset 详细见 readme属性细说

**Comment by maoxiandemeng** [comment]
stickOffset值和top区域的值一样大

**Comment by maoxiandemeng** [comment]
我运行你的Demo有问题，当我切换到ScrollView和GridView时会报类型转化异常，
java.lang.ClassCastException: in.srain.cube.views.GridViewWithHeaderAndFooter$HeaderViewGridAdapter cannot be cast to android.widget.BaseAdapter

**Comment by ta893115871** [comment]
java.lang.ClassCastException: in.srain.cube.views.GridViewWithHeaderAndFooter$HeaderViewGridAdapter cannot be cast to android.widget.BaseAdapter

这个是由于使用GridViewWithHeaderAndFooter不当造成的，这个已经改了，你更新下代码

**Comment by maoxiandemeng** [comment]
怎么添加上拉加载更多功能

**Comment by ta893115871** [comment]
@maoxiandemeng   怎么添加上拉加载更多功能  ？  可以监听listview的滚动事件，根据最后一条可见位置处理逻辑
